export const USERNAME_MAX_LENGTH = 32;
export const COMMUNITY_NAME_MAX_LENGTH = 60;
export const COMMUNITY_DESCRIPTION_MAX_LENGTH = 280;
export const POST_TITLE_MAX_LENGTH = 120;
export const POST_CONTENT_MAX_LENGTH = 5000;
export const COMMENT_CONTENT_MAX_LENGTH = 2000;
